# Generated by Django 4.1.1 on 2024-11-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
